export const COMMON_SUGGESTIONS = [
  // North America
  { type: 'Airport' as const, label: 'John F. Kennedy International, New York (JFK)', code: 'JFK' },
  { type: 'Airport' as const, label: 'Los Angeles International, Los Angeles (LAX)', code: 'LAX' },
  { type: 'Airport' as const, label: 'O\'Hare International, Chicago (ORD)', code: 'ORD' },
  { type: 'Airport' as const, label: 'Hartsfield–Jackson Atlanta International, Atlanta (ATL)', code: 'ATL' },
  { type: 'Airport' as const, label: 'Dallas/Fort Worth International, Dallas (DFW)', code: 'DFW' },
  { type: 'Airport' as const, label: 'San Francisco International, San Francisco (SFO)', code: 'SFO' },
  { type: 'Airport' as const, label: 'Miami International, Miami (MIA)', code: 'MIA' },
  { type: 'Airport' as const, label: 'Seattle–Tacoma International, Seattle (SEA)', code: 'SEA' },
  { type: 'Airport' as const, label: 'Denver International, Denver (DEN)', code: 'DEN' },
  { type: 'Airport' as const, label: 'Boston Logan International, Boston (BOS)', code: 'BOS' },
  { type: 'Airport' as const, label: 'Newark Liberty International, Newark (EWR)', code: 'EWR' },
  { type: 'Airport' as const, label: 'LaGuardia Airport, New York (LGA)', code: 'LGA' },
  { type: 'Airport' as const, label: 'Las Vegas Harry Reid International, Las Vegas (LAS)', code: 'LAS' },
  { type: 'Airport' as const, label: 'Washington Dulles International, Washington D.C. (IAD)', code: 'IAD' },
  { type: 'Airport' as const, label: 'Ronald Reagan Washington National, Washington D.C. (DCA)', code: 'DCA' },
  { type: 'Airport' as const, label: 'Toronto Pearson International, Toronto (YYZ)', code: 'YYZ' },
  { type: 'Airport' as const, label: 'Vancouver International, Vancouver (YVR)', code: 'YVR' },
  { type: 'Airport' as const, label: 'Montreal–Trudeau International, Montreal (YUL)', code: 'YUL' },
  { type: 'Airport' as const, label: 'Calgary International, Calgary (YYC)', code: 'YYC' },
  { type: 'Airport' as const, label: 'Benito Juárez International, Mexico City (MEX)', code: 'MEX' },
  { type: 'Airport' as const, label: 'Cancún International, Cancún (CUN)', code: 'CUN' },
  { type: 'Airport' as const, label: 'Monterrey International, Monterrey (MTY)', code: 'MTY' },
  { type: 'Airport' as const, label: 'Los Cabos International, San José del Cabo (SJD)', code: 'SJD' },

  // South America
  { type: 'Airport' as const, label: 'Guarulhos International, São Paulo (GRU)', code: 'GRU' },
  { type: 'Airport' as const, label: 'Galeão International, Rio de Janeiro (GIG)', code: 'GIG' },
  { type: 'Airport' as const, label: 'Ministro Pistarini International, Buenos Aires (EZE)', code: 'EZE' },
  { type: 'Airport' as const, label: 'Comodoro Arturo Merino Benítez International, Santiago (SCL)', code: 'SCL' },
  { type: 'Airport' as const, label: 'El Dorado International, Bogotá (BOG)', code: 'BOG' },
  { type: 'Airport' as const, label: 'Jorge Chávez International, Lima (LIM)', code: 'LIM' },

  // Europe
  { type: 'Airport' as const, label: 'Heathrow Airport, London (LHR)', code: 'LHR' },
  { type: 'Airport' as const, label: 'Gatwick Airport, London (LGW)', code: 'LGW' },
  { type: 'Airport' as const, label: 'Manchester Airport, Manchester (MAN)', code: 'MAN' },
  { type: 'Airport' as const, label: 'Charles de Gaulle Airport, Paris (CDG)', code: 'CDG' },
  { type: 'Airport' as const, label: 'Orly Airport, Paris (ORY)', code: 'ORY' },
  { type: 'Airport' as const, label: 'Frankfurt Airport, Frankfurt (FRA)', code: 'FRA' },
  { type: 'Airport' as const, label: 'Munich Airport, Munich (MUC)', code: 'MUC' },
  { type: 'Airport' as const, label: 'Berlin Brandenburg Airport, Berlin (BER)', code: 'BER' },
  { type: 'Airport' as const, label: 'Amsterdam Airport Schiphol, Amsterdam (AMS)', code: 'AMS' },
  { type: 'Airport' as const, label: 'Madrid–Barajas Airport, Madrid (MAD)', code: 'MAD' },
  { type: 'Airport' as const, label: 'Barcelona–El Prat Airport, Barcelona (BCN)', code: 'BCN' },
  { type: 'Airport' as const, label: 'Lisbon Airport, Lisbon (LIS)', code: 'LIS' },
  { type: 'Airport' as const, label: 'Rome Fiumicino Airport, Rome (FCO)', code: 'FCO' },
  { type: 'Airport' as const, label: 'Milan Malpensa Airport, Milan (MXP)', code: 'MXP' },
  { type: 'Airport' as const, label: 'Venice Marco Polo Airport, Venice (VCE)', code: 'VCE' },
  { type: 'Airport' as const, label: 'Zurich Airport, Zurich (ZRH)', code: 'ZRH' },
  { type: 'Airport' as const, label: 'Geneva Airport, Geneva (GVA)', code: 'GVA' },
  { type: 'Airport' as const, label: 'Vienna International Airport, Vienna (VIE)', code: 'VIE' },
  { type: 'Airport' as const, label: 'Brussels Airport, Brussels (BRU)', code: 'BRU' },
  { type: 'Airport' as const, label: 'Dublin Airport, Dublin (DUB)', code: 'DUB' },
  { type: 'Airport' as const, label: 'Copenhagen Airport, Copenhagen (CPH)', code: 'CPH' },
  { type: 'Airport' as const, label: 'Oslo Airport, Oslo (OSL)', code: 'OSL' },
  { type: 'Airport' as const, label: 'Stockholm Arlanda Airport, Stockholm (ARN)', code: 'ARN' },
  { type: 'Airport' as const, label: 'Helsinki-Vantaa Airport, Helsinki (HEL)', code: 'HEL' },
  { type: 'Airport' as const, label: 'Warsaw Chopin Airport, Warsaw (WAW)', code: 'WAW' },
  { type: 'Airport' as const, label: 'Václav Havel Airport, Prague (PRG)', code: 'PRG' },
  { type: 'Airport' as const, label: 'Budapest Ferenc Liszt International Airport, Budapest (BUD)', code: 'BUD' },
  { type: 'Airport' as const, label: 'Kraków John Paul II International Airport, Kraków (KRK)', code: 'KRK' },
  { type: 'Airport' as const, label: 'Athens International Airport, Athens (ATH)', code: 'ATH' },
  { type: 'Airport' as const, label: 'Istanbul Airport, Istanbul (IST)', code: 'IST' },
  { type: 'Airport' as const, label: 'Istanbul Sabiha Gökçen International Airport, Istanbul (SAW)', code: 'SAW' },
  { type: 'Airport' as const, label: 'Antalya Airport, Antalya (AYT)', code: 'AYT' },
  { type: 'Airport' as const, label: 'Belgrade Nikola Tesla Airport, Belgrade (BEG)', code: 'BEG' },
  { type: 'Airport' as const, label: 'Bucharest Henri Coandă International Airport, Bucharest (OTP)', code: 'OTP' },
  { type: 'Airport' as const, label: 'Sofia Airport, Sofia (SOF)', code: 'SOF' },
  { type: 'Airport' as const, label: 'Ljubljana Jože Pučnik Airport, Ljubljana (LJU)', code: 'LJU' },

  // Middle East & Africa
  { type: 'Airport' as const, label: 'Dubai International, Dubai (DXB)', code: 'DXB' },
  { type: 'Airport' as const, label: 'Abu Dhabi International, Abu Dhabi (AUH)', code: 'AUH' },
  { type: 'Airport' as const, label: 'Hamad International, Doha (DOH)', code: 'DOH' },
  { type: 'Airport' as const, label: 'King Abdulaziz International, Jeddah (JED)', code: 'JED' },
  { type: 'Airport' as const, label: 'King Khalid International, Riyadh (RUH)', code: 'RUH' },
  { type: 'Airport' as const, label: 'Muscat International, Muscat (MCT)', code: 'MCT' },
  { type: 'Airport' as const, label: 'Kuwait International, Kuwait City (KWI)', code: 'KWI' },
  { type: 'Airport' as const, label: 'Bahrain International, Manama (BAH)', code: 'BAH' },
  { type: 'Airport' as const, label: 'Ben Gurion International, Tel Aviv (TLV)', code: 'TLV' },
  { type: 'Airport' as const, label: 'Cairo International, Cairo (CAI)', code: 'CAI' },
  { type: 'Airport' as const, label: 'O.R. Tambo International, Johannesburg (JNB)', code: 'JNB' },
  { type: 'Airport' as const, label: 'Cape Town International, Cape Town (CPT)', code: 'CPT' },
  { type: 'Airport' as const, label: 'Nairobi Jomo Kenyatta International, Nairobi (NBO)', code: 'NBO' },
  { type: 'Airport' as const, label: 'Bole International, Addis Ababa (ADD)', code: 'ADD' },
  { type: 'Airport' as const, label: 'Mohammed V International, Casablanca (CMN)', code: 'CMN' },
  { type: 'Airport' as const, label: 'Lagos Murtala Muhammed International, Lagos (LOS)', code: 'LOS' },

  // South Asia
  { type: 'Airport' as const, label: 'Indira Gandhi International Airport, New Delhi (DEL)', code: 'DEL' },
  { type: 'Airport' as const, label: 'Chhatrapati Shivaji Maharaj International Airport, Mumbai (BOM)', code: 'BOM' },
  { type: 'Airport' as const, label: 'Kempegowda International Airport, Bengaluru (BLR)', code: 'BLR' },
  { type: 'Airport' as const, label: 'Rajiv Gandhi International Airport, Hyderabad (HYD)', code: 'HYD' },
  { type: 'Airport' as const, label: 'Chennai International Airport, Chennai (MAA)', code: 'MAA' },
  { type: 'Airport' as const, label: 'Netaji Subhas Chandra Bose International, Kolkata (CCU)', code: 'CCU' },
  { type: 'Airport' as const, label: 'Cochin International Airport, Kochi (COK)', code: 'COK' },
  { type: 'Airport' as const, label: 'Sardar Vallabhbhai Patel International, Ahmedabad (AMD)', code: 'AMD' },
  { type: 'Airport' as const, label: 'Lohegaon Airport, Pune (PNQ)', code: 'PNQ' },
  { type: 'Airport' as const, label: 'Goa International Airport, Goa (GOI)', code: 'GOI' },
  { type: 'Airport' as const, label: 'Sheikh ul-Alam International, Srinagar (SXR)', code: 'SXR' },
  { type: 'Airport' as const, label: 'Jaipur International Airport, Jaipur (JAI)', code: 'JAI' },
  { type: 'Airport' as const, label: 'Amritsar Sri Guru Ram Dass Jee International, Amritsar (ATQ)', code: 'ATQ' },
  { type: 'Airport' as const, label: 'Hazrat Shahjalal International, Dhaka (DAC)', code: 'DAC' },
  { type: 'Airport' as const, label: 'Tribhuvan International, Kathmandu (KTM)', code: 'KTM' },
  { type: 'Airport' as const, label: 'Bandaranaike International, Colombo (CMB)', code: 'CMB' },
  { type: 'Airport' as const, label: 'Allama Iqbal International, Lahore (LHE)', code: 'LHE' },
  { type: 'Airport' as const, label: 'Jinnah International, Karachi (KHI)', code: 'KHI' },
  { type: 'Airport' as const, label: 'Islamabad International, Islamabad (ISB)', code: 'ISB' },

  // East & Southeast Asia
  { type: 'Airport' as const, label: 'Haneda Airport, Tokyo (HND)', code: 'HND' },
  { type: 'Airport' as const, label: 'Narita International, Tokyo (NRT)', code: 'NRT' },
  { type: 'Airport' as const, label: 'Incheon International, Seoul (ICN)', code: 'ICN' },
  { type: 'Airport' as const, label: 'Beijing Capital International, Beijing (PEK)', code: 'PEK' },
  { type: 'Airport' as const, label: 'Beijing Daxing International, Beijing (PKX)', code: 'PKX' },
  { type: 'Airport' as const, label: 'Shanghai Pudong International, Shanghai (PVG)', code: 'PVG' },
  { type: 'Airport' as const, label: 'Hong Kong International, Hong Kong (HKG)', code: 'HKG' },
  { type: 'Airport' as const, label: 'Singapore Changi Airport, Singapore (SIN)', code: 'SIN' },
  { type: 'Airport' as const, label: 'Suvarnabhumi Airport, Bangkok (BKK)', code: 'BKK' },
  { type: 'Airport' as const, label: 'Kuala Lumpur International, Kuala Lumpur (KUL)', code: 'KUL' },
  { type: 'Airport' as const, label: 'Nguyen Van Troi Airport, Ho Chi Minh City (SGN)', code: 'SGN' },
  { type: 'Airport' as const, label: 'Ninoy Aquino International, Manila (MNL)', code: 'MNL' },
  { type: 'Airport' as const, label: 'Soekarno-Hatta International, Jakarta (CGK)', code: 'CGK' },
  { type: 'Airport' as const, label: 'Guangzhou Baiyun International, Guangzhou (CAN)', code: 'CAN' },
  { type: 'Airport' as const, label: 'Shenzhen Bao\'an International, Shenzhen (SZX)', code: 'SZX' },
  { type: 'Airport' as const, label: 'Chengdu Tianfu International, Chengdu (TFU)', code: 'TFU' },
  { type: 'Airport' as const, label: 'Taipei Taoyuan International, Taipei (TPE)', code: 'TPE' },

  // Australia & Oceania
  { type: 'Airport' as const, label: 'Sydney Kingsford Smith Airport, Sydney (SYD)', code: 'SYD' },
  { type: 'Airport' as const, label: 'Melbourne Airport, Melbourne (MEL)', code: 'MEL' },
  { type: 'Airport' as const, label: 'Brisbane Airport, Brisbane (BNE)', code: 'BNE' },
  { type: 'Airport' as const, label: 'Perth Airport, Perth (PER)', code: 'PER' },
  { type: 'Airport' as const, label: 'Auckland Airport, Auckland (AKL)', code: 'AKL' },
];

export const IATA_TO_CITY_MAP: Record<string, string> = {
  // North America
  'JFK': 'New York',
  'LAX': 'Los Angeles',
  'ORD': 'Chicago',
  'ATL': 'Atlanta',
  'DFW': 'Dallas',
  'SFO': 'San Francisco',
  'MIA': 'Miami',
  'SEA': 'Seattle',
  'DEN': 'Denver',
  'BOS': 'Boston',
  'EWR': 'Newark',
  'LGA': 'New York',
  'LAS': 'Las Vegas',
  'IAD': 'Washington D.C.',
  'DCA': 'Washington D.C.',
  'YYZ': 'Toronto',
  'YVR': 'Vancouver',
  'YUL': 'Montreal',
  'YYC': 'Calgary',
  'MEX': 'Mexico City',
  'CUN': 'Cancún',
  'MTY': 'Monterrey',
  'SJD': 'San José del Cabo',

  // South America
  'GRU': 'São Paulo',
  'GIG': 'Rio de Janeiro',
  'EZE': 'Buenos Aires',
  'SCL': 'Santiago',
  'BOG': 'Bogotá',
  'LIM': 'Lima',

  // Europe
  'LHR': 'London',
  'LGW': 'London',
  'MAN': 'Manchester',
  'CDG': 'Paris',
  'ORY': 'Paris',
  'FRA': 'Frankfurt',
  'MUC': 'Munich',
  'BER': 'Berlin',
  'AMS': 'Amsterdam',
  'MAD': 'Madrid',
  'BCN': 'Barcelona',
  'LIS': 'Lisbon',
  'FCO': 'Rome',
  'MXP': 'Milan',
  'VCE': 'Venice',
  'ZRH': 'Zurich',
  'GVA': 'Geneva',
  'VIE': 'Vienna',
  'BRU': 'Brussels',
  'DUB': 'Dublin',
  'CPH': 'Copenhagen',
  'OSL': 'Oslo',
  'ARN': 'Stockholm',
  'HEL': 'Helsinki',
  'WAW': 'Warsaw',
  'PRG': 'Prague',
  'BUD': 'Budapest',
  'KRK': 'Kraków',
  'ATH': 'Athens',
  'IST': 'Istanbul',
  'SAW': 'Istanbul',
  'AYT': 'Antalya',
  'BEG': 'Belgrade',
  'OTP': 'Bucharest',
  'SOF': 'Sofia',
  'LJU': 'Ljubljana',

  // Middle East & Africa
  'DXB': 'Dubai',
  'AUH': 'Abu Dhabi',
  'DOH': 'Doha',
  'JED': 'Jeddah',
  'RUH': 'Riyadh',
  'MCT': 'Muscat',
  'KWI': 'Kuwait City',
  'BAH': 'Manama',
  'TLV': 'Tel Aviv',
  'CAI': 'Cairo',
  'JNB': 'Johannesburg',
  'CPT': 'Cape Town',
  'NBO': 'Nairobi',
  'ADD': 'Addis Ababa',
  'CMN': 'Casablanca',
  'LOS': 'Lagos',

  // South Asia
  'DEL': 'New Delhi',
  'BOM': 'Mumbai',
  'BLR': 'Bengaluru',
  'HYD': 'Hyderabad',
  'MAA': 'Chennai',
  'CCU': 'Kolkata',
  'COK': 'Kochi',
  'AMD': 'Ahmedabad',
  'PNQ': 'Pune',
  'GOI': 'Goa',
  'SXR': 'Srinagar',
  'JAI': 'Jaipur',
  'ATQ': 'Amritsar',
  'LKO': 'Lucknow',
  'PAT': 'Patna',
  'IXC': 'Chandigarh',
  'BBI': 'Bhubaneswar',
  'TRV': 'Thiruvananthapuram',
  'DAC': 'Dhaka',
  'KTM': 'Kathmandu',
  'CMB': 'Colombo',
  'LHE': 'Lahore',
  'KHI': 'Karachi',
  'ISB': 'Islamabad',

  // East & Southeast Asia
  'HND': 'Tokyo',
  'NRT': 'Tokyo',
  'ICN': 'Seoul',
  'PEK': 'Beijing',
  'PKX': 'Beijing',
  'PVG': 'Shanghai',
  'HKG': 'Hong Kong',
  'SIN': 'Singapore',
  'BKK': 'Bangkok',
  'KUL': 'Kuala Lumpur',
  'SGN': 'Ho Chi Minh City',
  'MNL': 'Manila',
  'CGK': 'Jakarta',
  'CAN': 'Guangzhou',
  'SZX': 'Shenzhen',
  'TFU': 'Chengdu',
  'TPE': 'Taipei',

  // Australia & Oceania
  'SYD': 'Sydney',
  'MEL': 'Melbourne',
  'BNE': 'Brisbane',
  'PER': 'Perth',
  'AKL': 'Auckland',
};
