export const COMMON_SUGGESTIONS = [
  { type: 'Airport' as const, label: 'John F. Kennedy International, New York (JFK)', code: 'JFK' },
  { type: 'Airport' as const, label: 'Heathrow Airport, London (LHR)', code: 'LHR' },
  { type: 'Airport' as const, label: 'Los Angeles International, Los Angeles (LAX)', code: 'LAX' },
  { type: 'Airport' as const, label: 'Dubai International, Dubai (DXB)', code: 'DXB' },
  { type: 'Airport' as const, label: 'Frankfurt Airport, Frankfurt (FRA)', code: 'FRA' },
  { type: 'Airport' as const, label: 'Haneda Airport, Tokyo (HND)', code: 'HND' },
  { type: 'Airport' as const, label: 'Kempegowda International Airport Bengaluru (BLR)', code: 'BLR' },
  { type: 'Airport' as const, label: 'Indira Gandhi International Airport, New Delhi (DEL)', code: 'DEL' },
  { type: 'Airport' as const, label: 'Chhatrapati Shivaji Maharaj International Airport, Mumbai (BOM)', code: 'BOM' },
  { type: 'Airport' as const, label: 'Rajiv Gandhi International Airport, Hyderabad (HYD)', code: 'HYD' },
  { type: 'Airport' as const, label: 'Benito Juárez International Airport, Mexico City (MEX)', code: 'MEX' },
  { type: 'Airport' as const, label: 'Cancún International Airport, Cancún (CUN)', code: 'CUN' },
  { type: 'Airport' as const, label: 'Los Cabos International Airport, San José del Cabo (SJD)', code: 'SJD' },
  { type: 'Airport' as const, label: 'Amsterdam Airport Schiphol, Amsterdam (AMS)', code: 'AMS' },
  { type: 'Airport' as const, label: 'Charles de Gaulle Airport, Paris (CDG)', code: 'CDG' },
  { type: 'Airport' as const, label: 'Monterrey International Airport, Monterrey (MTY)', code: 'MTY' },
  { type: 'Airport' as const, label: 'Munich Airport, Munich (MUC)', code: 'MUC' },
  { type: 'Airport' as const, label: 'Václav Havel Airport Prague, Prague (PRG)', code: 'PRG' },
  { type: 'Airport' as const, label: 'Frankfurt Airport, Frankfurt (FRA)', code: 'FRA' },
  { type: 'Airport' as const, label: 'Berlin Brandenburg Airport, Berlin (BER)', code: 'BER' },
  { type: 'Airport' as const, label: 'Barcelona–El Prat Airport, Barcelona (BCN)', code: 'BCN' },
  { type: 'Airport' as const, label: 'Madrid–Barajas Airport, Madrid (MAD)', code: 'MAD' },
  { type: 'Airport' as const, label: 'Lisbon Airport, Lisbon (LIS)', code: 'LIS' },
  { type: 'Airport' as const, label: 'Vienna International Airport, Vienna (VIE)', code: 'VIE' },
  { type: 'Airport' as const, label: 'Zurich Airport, Zurich (ZRH)', code: 'ZRH' },
  { type: 'Airport' as const, label: 'Geneva Airport, Geneva (GVA)', code: 'GVA' },
  { type: 'Airport' as const, label: 'Istanbul Airport, Istanbul (IST)', code: 'IST' },
  { type: 'Airport' as const, label: 'Dublin Airport, Dublin (DUB)', code: 'DUB' },
  { type: 'Airport' as const, label: 'Warsaw Chopin Airport, Warsaw (WAW)', code: 'WAW' },
  { type: 'Airport' as const, label: 'Brussels Airport, Brussels (BRU)', code: 'BRU' },
  { type: 'Airport' as const, label: 'Prague Václav Havel Airport, Prague (PRG)', code: 'PRG' },
  { type: 'Airport' as const, label: 'Copenhagen Airport, Copenhagen (CPH)', code: 'CPH' },
  { type: 'Airport' as const, label: 'Oslo Airport, Oslo (OSL)', code: 'OSL' },
  { type: 'Airport' as const, label: 'Stockholm Arlanda Airport, Stockholm (ARN)', code: 'ARN' },
  { type: 'Airport' as const, label: 'Helsinki-Vantaa Airport, Helsinki (HEL)', code: 'HEL' },
  { type: 'Airport' as const, label: 'Budapest Ferenc Liszt International Airport, Budapest (BUD)', code: 'BUD' },
  { type: 'Airport' as const, label: 'Kraków John Paul II International Airport, Kraków (KRK)', code: 'KRK' },
  { type: 'Airport' as const, label: 'Venice Marco Polo Airport, Venice (VCE)', code: 'VCE' },
  { type: 'Airport' as const, label: 'Milan Malpensa Airport, Milan (MXP)', code: 'MXP' },
  { type: 'Airport' as const, label: 'Ljubljana Jože Pučnik Airport, Ljubljana (LJU)', code: 'LJU' },
  { type: 'Airport' as const, label: 'Belgrade Nikola Tesla Airport, Belgrade (BEG)', code: 'BEG' },
  { type: 'Airport' as const, label: 'Sofia Airport, Sofia (SOF)', code: 'SOF' },
  { type: 'Airport' as const, label: 'Bucharest Henri Coandă International Airport, Bucharest (OTP)', code: 'OTP' },
  { type: 'Airport' as const, label: 'Athens International Airport, Athens (ATH)', code: 'ATH' },
  { type: 'Airport' as const, label: 'Istanbul Sabiha Gökçen International Airport, Istanbul (SAW)', code: 'SAW' },
  { type: 'Airport' as const, label: 'Antalya Airport, Antalya (AYT)', code: 'AYT' }
  { type: 'Flight' as const, label: 'American Airlines Flight 123 (AA123)', code: 'AA123' },
  { type: 'Flight' as const, label: 'Delta Airlines Flight 456 (DL456)', code: 'DL456' },
  { type: 'Flight' as const, label: 'Emirates Flight 1 (EK1)', code: 'EK1' },
  { type: 'Flight' as const, label: 'British Airways Flight 99 (BA99)', code: 'BA99' }
];

export const IATA_TO_CITY_MAP: Record<string, string> = {
  'DEL': 'New Delhi',
  'BOM': 'Mumbai',
  'BLR': 'Bengaluru',
  'HYD': 'Hyderabad',
  'MAA': 'Chennai',
  'CCU': 'Kolkata',
  'LHR': 'London',
  'JFK': 'New York',
  'DXB': 'Dubai',
  'SIN': 'Singapore',
  'SFO': 'San Francisco',
  'LAX': 'Los Angeles',
  'EWR': 'Newark',
  'FRA': 'Frankfurt',
  'CDG': 'Paris',
  'AMS': 'Amsterdam',
  'SYD': 'Sydney',
  'YYZ': 'Toronto',
  'MEX': 'Mexico City',
  'IST': 'Istanbul',
  'DUB': 'Dublin',
  'WAW': 'Warsaw',
  'BRU': 'Brussels',
  'PRG': 'Prague',
  'CPH': 'Copenhagen',
  'OSL': 'Oslo',
  'ARN': 'Stockholm',
  'HEL': 'Helsinki',
  'BUD': 'Budapest',
  'KRK': 'Kraków',
  'VCE': 'Venice',
  'MXP': 'Milan Malpensa',
  'LJU': 'Ljubljana',
  'BEG': 'Belgrade',
  'SOF': 'Sofia',
  'OTP': 'Bucharest',
  'ATH': 'Athens',
  'SAW': 'Istanbul Sabiha Gökçen',
  'AYT': 'Antalya',
  'MTY': 'Monterrey',
  'AMS': 'Amsterdam',
  'SYD': 'Sydney',
  'YYZ': 'Toronto',
  'MEX': 'Mexico City',
  'IST': 'Istanbul',
  'DUB': 'Dublin',
  'WAW': 'Warsaw',
  'BRU': 'Brussels',
  'PRG': 'Prague',
  'CPH': 'Copenhagen',
  'OSL': 'Oslo',
  'ARN': 'Stockholm',
  'HEL': 'Helsinki',
  'BUD': 'Budapest',
  'KRK': 'Kraków',
  'VCE': 'Venice',
  'MXP': 'Milan Malpensa',
  'LJU': 'Ljubljana',
  'BEG': 'Belgrade',
  'SOF': 'Sofia',
  'OTP': 'Bucharest',
  'ATH': 'Athens',
  'SAW': 'Istanbul Sabiha Gökçen',
  'AYT': 'Antalya'
};
